name: ad_common
description: A new Flutter package.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: 3.0.1
  convert: 3.0.1
  connectivity: 3.0.6
  collection: 1.15.0
  dio: 4.0.0
  dio_cookie_manager: 2.0.0
  device_info_plus: 2.1.0
  flutter_easyrefresh: 2.2.1
  flutter_easyloading: 3.0.3
  flutter_screenutil: 5.0.2
  fluttertoast: 8.0.8
  intl: 0.17.0
  package_info_plus: 1.3.0
  permission_handler: 8.2.2
  path_provider: 2.0.5
  provider: 6.0.1
  shared_preferences: 2.0.11
  synchronized: 3.0.0
  sqflite: 2.0.0+4
  uuid: 3.0.5

  # 定制化插件需求 null-safety
  screenshot_callback:
    git:
      url: https://github.com/windows7lake/flutter_screenshot_callback.git

  flutter_keychain:
    git:
      url: https://github.com/StanleyCocos/flutter_keychain.git




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
